# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: harvardnlp
email: nlp.harvard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Home of the Harvard SEAS natural-language processing group.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nlp.seas.harvard.edu/" # the base hostname & protocol for your site
twitter_username: harvardnlp
github_username:  harvardnlp

# Build settings
markdown: kramdown
highlighter: rouge
